// EBNF to Railroad Diagrams: https://www.bottlecaps.de/rr/ui

regex ::= alternative

alternative ::= concatenation ('|' concatenation)*

concatenation ::= repetition repetition*

repetition ::= term ('*' | '+' | '?' | repetitionMinMax)*

repetitionMinMax ::= '{' INTEGER (',' INTEGER)? '}'

term ::= '^' | '$' | '.' | CHAR | group | backreference | '(?=' regex ')' | '(?!' regex ')' | '(' regex ')'

group ::= '[' '^'? (characterRange | CHAR)+ ']'

characterRange ::= CHAR '-' CHAR

backreference ::= '\' ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9')

<?TOKENS?>

CHAR ::= [^(){}^$*+?|.#x5b#x5d] |
    '\' ('[' | ']' | '(' | ')' | '{' | '}' | '^' | '$' | '*' | '+' | '?' | '.' | '|' | '\')

INTEGER ::= [0-9]+
